"use strict";
let a = 10;
let b = 20;
let sum = a + b;
console.log("Sum :", sum);
let r = 4;
let pi = 1.4;
let area = pi * r * r;
console.log("Area : ", area);
let m = 7.9;
console.log(m);
let nam = "Likhita";
console.log("Name:", nam);
let firstName = "Likhita";
let lastName = "Grandhi";
let fullName = firstName + " " + lastName;
console.log("Full Name:", fullName);
let cou = "TypeScript";
console.log("Length =", cou.length);
let isFriend = true;
console.log(isFriend);
let age = 19;
let eligible = age >= 18;
console.log("Eligible to Vote:", eligible);
let notFriend = false;
console.log(notFriend);
